#!/bin/bash
if [[ "$PWD" == *"/node_modules/"* ]]; then
  DIR=~/tmp/@itrocks/template-insight
  mkdir -p DIR
  rm -rf $DIR/test
  rsync -aP ./ $DIR/ --exclude='.git' --exclude='.gitignore'
  cd $DIR || exit 1
  npm install
fi
npx jest
